package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"strconv"
	"time"

	"github.com/levelstudio/payroll-4ta-crud/pkg/models"
)

// ID is the resolver for the id field.
func (r *productResolver) ID(ctx context.Context, obj *models.Product) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *productResolver) CreatedAt(ctx context.Context, obj *models.Product) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *productResolver) UpdatedAt(ctx context.Context, obj *models.Product) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
