package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"strconv"
	"time"

	"github.com/levelstudio/payroll-4ta-crud/pkg/models"
)

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// Mayor is the resolver for the mayor field.
func (r *userResolver) Mayor(ctx context.Context, obj *models.User) (string, error) {
	age, err := strconv.Atoi(obj.Age)
	if err != nil {
		panic(err)
	}

	if age < 18 {
		return "menor de edad", nil
	} else {
		return "mayor de edad", nil
	}
}

// CreatedAt is the resolver for the created_at field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
