// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	Name string `json:"name"`
	Age  string `json:"age"`
}

type Query struct {
}

type UpdateUser struct {
	Name *string `json:"name,omitempty"`
	Age  *string `json:"age,omitempty"`
}
