// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProduct struct {
	Name  string `json:"name"`
	Price string `json:"price"`
}

type Query struct {
}

type UpdateProduct struct {
	Name  *string `json:"name,omitempty"`
	Price *string `json:"price,omitempty"`
}
